Multiple databases support with database option
elixir-mongo/mongodb pull request #103
Opened 2017-02-03 04:33 UTC by deepblue

In some case, we want to access multiple databases within one session. 
It can be a database migration task, or some team has logically separated databases in one instance for any reason. My team manually sharded databases in our rules, and it's not efficient to make a connection per each database.

In this PR, I added `opts[:database]` options to protocol commands, and it allows to access other databases.

I'm not quite sure this is the best implementation, so please advise me if you have any idea.

Thanks!

2017-02-03 11:21 UTC, ericmj requested changes

2017-02-03 11:21 UTC, ericmj commented on lib/mongo/protocol/utils.ex
> +  def namespace(coll, s, database \\ nil)
Maybe we should make the last argument explicit so that we don't forget to pass it somewhere?

2017-02-03 11:21 UTC, ericmj commented on lib/mongo/protocol/utils.ex
> +  def namespace(coll, s, database) when is_nil(database),
Pattern match on `nil` instead: `def namespace(coll, s, nil)`.

2017-02-03 21:19 UTC, deepblue commented on lib/mongo/protocol/utils.ex
> +  def namespace(coll, s, database \\ nil)
Now the last parameter is explicit and can be nil

2017-02-03 21:19 UTC, deepblue commented on lib/mongo/protocol/utils.ex
> +  def namespace(coll, s, database) when is_nil(database),
Changed to use pattern matching. Good catch!

2017-02-03 21:20 UTC, deepblue commented
@ericmj Thanks for reviewing the PR!

2017-02-04 11:14 UTC, ericmj approved these changes
Thank you!

2017-02-04 11:14 UTC, merged