feature: find_one
elixir-mongo/mongodb pull request #104
Opened 2017-02-08 12:12 UTC by tomjoro

#29 

Mongodb protocol only has find. find_one is done by just taking the first document using natural order returned from find (as per mongo documentation).

I'm not sure about the applicability of all the options.

2017-02-09 14:14 UTC, ericmj requested changes

2017-02-09 14:14 UTC, ericmj commented on lib/mongo.ex
> +  end
It looks like we can do

```elixir
opts =
  opts
  |> Keyword.delete(:order_by)
  |> Keyword.put(opts, :limit, 1)
find(conn, coll, filter, opts)
|> Enum.at(0)
```

But please correct me if there are other differences.

2017-02-09 14:14 UTC, ericmj commented on lib/mongo.ex
> +
✂️ this line.

2017-02-09 14:14 UTC, ericmj commented on lib/mongo.ex
> +  Selects document a single document in a collection and returns either a document
✂️ first "document".

2017-02-09 14:14 UTC, ericmj commented on lib/mongo.ex
> +
✂️ this line.

2017-02-09 14:14 UTC, ericmj commented on test/mongo_test.exs
> +  end
Since the asserts are still single line we can remove the empty lines around them.

2017-02-09 16:12 UTC, tomjoro commented on lib/mongo.ex
> +  end
I had also removed the modifier.  Not 100% sure how the modifier works.
      {"$orderby", opts[:sort]}

Enum.at(0) will return "0" if the cursor is empty, so I don't think "find" will work, so I think it must be it's own function.

2017-02-09 16:14 UTC, ericmj commented on lib/mongo.ex
> +  end
You can drop `:sort` from the opts keyword also. `Enum.at(enum, 0)` will return `nil` if the enum is empty.

2017-02-09 16:20 UTC, tomjoro commented on lib/mongo.ex
> +  end
I guess we could just "find", but would we then replace the entire body of "find_one" with "find"?  I can try that...

2017-02-09 16:38 UTC, tomjoro commented
Enum.at(cursor, 0) doesn't return nil if empty. It returns 0.

2017-02-09 16:40 UTC, ericmj commented
> Enum.at(cursor, 0) doesn't return nil if empty. It returns 0.

If it returns `0` then there is an element with value `0` at the first position in the cursor or there is some weird bug in the cursor that would make it return `0` if the cursor returns no results.

```elixir
iex(1)> Enum.at([], 0)
nil
```

2017-02-09 18:28 UTC, tomjoro commented
The following is a passing test:
```
  test "find_is_zero", c do
    coll = unique_name()
    assert 0 == Mongo.find(c.pid, coll, %{}) |> Enum.at(0)
  end
```

2017-02-10 13:12 UTC, ericmj commented
The test above fails with the following for me:

```
1) test find_is_zero (Mongo.Test)
     test/mongo_test.exs:142
     Assertion with == failed
     code:  0 == Mongo.find(c.pid(), coll, %{}) |> Enum.at(0)
     left:  0
     right: nil
     stacktrace:
       test/mongo_test.exs:144: (test)
```

What elixir version are you using?

2017-02-10 13:17 UTC, tomjoro commented
I am using 1.3.2.

2017-02-10 13:29 UTC, tomjoro commented
Looks like I based on an older branch. My bad. I'll fix this and generate a new proper pull request. I suspect it will work then :)

2017-02-10 14:17 UTC, ericmj commented
I bisected and found this commit to fix the bug: https://github.com/elixir-lang/elixir/commit/6f242e7cc27c1956f7f6dece7e38e66a3f2366df. It's a fix we forgot to backport to the v1.3 bugfix branch :(.

> I'll fix this and generate a new proper pull request. I suspect it will work then :)

I don't want to bump the version requirement so keeping your current code is better but please add a note that we should change to Enum.at/2 when we require 1.4.0+.

2017-02-10 14:31 UTC, tomjoro commented
You can close/delete this pull request.

I created a new pull requests #105 to get rid of the wrong base for this pull request. But the Enum.at(0) is still returning 0. I wonder if this can be a MongoDB thing?

2017-02-10 14:31 UTC, closed without merging

2017-02-10 14:34 UTC, ericmj commented
`Enum.at` was fixed in Elixir 1.4.0, if you use 1.4.0+ you shouldn't get the bug.

You based the PR of the correct branch.

2017-02-10 14:38 UTC, tomjoro commented
Ok. I was unsure so I thought best to make a clean pull request, since I locally had some old code which was committed. Can we continue this conversation on #105?

2017-02-10 14:39 UTC, ericmj commented
Sure!