Fix Elixir 1.11 dependency warnings
elixir-mongo/mongodb pull request #349
Opened 2020-10-22 14:13 UTC by nathanl

2020-10-22 20:50 UTC, hauleth requested changes

2020-10-22 20:50 UTC, hauleth commented on mix.exs
> +      extra_applications: [:crytpo, :logger, :ssl],
```suggestion
      extra_applications: [:crypto, :logger, :ssl],
```

2020-10-27 13:21 UTC, nathanl commented
@hauleth Whoops 😊. Thanks for fixing my clumsy mistake.

2020-10-30 10:02 UTC, hauleth approved these changes

2020-10-30 10:02 UTC, merged

2021-03-18 17:04 UTC, ricardoccpaiva commented
Hi @hauleth, any reason for `tags` to have stopped being created in the recent past? 
https://github.com/kobil-systems/mongodb/tags