WIP: Batch write implementation
elixir-mongo/mongodb pull request #76
Opened 2016-08-26 15:02 UTC by ShauneStark

2016-10-17 11:57 UTC, ericmj commented
db-conn has been merged into master and we will have new release out shortly. You can rebase this PR against master. What else is needed to finish this?

2016-12-02 22:52 UTC, ghost requested changes
Just a quick initial review

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +      resultbaselist = Enum.to_list(resultbaselist)
Use pipe here

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +      end
Replace lambda with `&BSON.encode/1`

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +        IO.iodata_length(x)
Replace lambda with `&IO.iodata_length/1`

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +      inserttemplate = %{inserttemplate | ordered: writeorder}
Combine these

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +      updatetemplate = %{updatetemplate | ordered: writeorder}
Combine these

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +      deletetemplate = %{deletetemplate | ordered: writeorder}
Combine these. Don't repeat yourself.

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +          case x.type do
Don't repeat yourself

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +    {:ok, mpid} = Mongo.start_link(hostname: "mongo1.hellodata.com", database: "test")
Don't reconnect each submission

2016-12-02 22:52 UTC, cjhowe commented on lib/mongobatch/mongobatch.ex
> +  def insert(insertdocument) do
Don't repeat yourself

2016-12-09 12:34 UTC, ericmj commented
Ping?

2016-12-09 15:42 UTC, cjhowe commented
Will be doing more review and refactoring on this shortly, but not until after the #93

2016-12-09 19:37 UTC, ericmj commented
Cool, didn't realise you were handling this PR @cjhowe.

2017-05-29 17:59 UTC, ankhers commented
Is there any update for this now that #124 has been merged?

2018-05-21 22:41 UTC, closed without merging

2018-07-12 17:42 UTC, ben-pr-p commented
What's the status of bulk write @ankhers ?

2018-07-12 19:25 UTC, ankhers commented
Unfortunately the original author stopped work on this. There has been no work on it since.

2018-07-12 19:34 UTC, ben-pr-p commented
Gotcha. Do you have an understanding what is required to finish it up?

2018-07-12 23:23 UTC, ankhers commented
Unfortunately I have never really gone through the code here, nor looked at the spec for this.